apiVersion: v1
kind: Service
metadata:
  name: kleaven-blog-service
spec:
  type: NodePort
  selector:
    app: kleaven-blog
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30050